config/routes.rb
Rails.application.routes.draw do
  resources :pets
  resources :users
  resources :favorites

  root "pets#show"
  get '/randompet' => 'pets#random'
  get '/favoritepet/:pet_id' => 'favorites#like', as: 'favorite_pet'
  get '/favorites' => 'favorites#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :pet
end

app/models/pet.rb
class Pet < ApplicationRecord
has_many :favorites

  def self.random
    all.shuffle.pop
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def like
    pet = Pet.find(params[:pet_id])
    favorite = Favorite.create(pet: pet, user: current_user)
    render json: Pet.random
  end

  def index
    if session[:user_id].nil?
      redirect_to '/signup'
    else
      # user = User.find(session[:user_id])
      @favorites = current_user.favorites
    end
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    # @pets = Pet.all
    @pets = PetCall.call({location: 'Broward'})
  end

  def random
    render json: Pet.random
  end
  # GET /pets/1
  # GET /pets/1.json
  def show
    # @pet = PetCall.random({location: 'Broward'})
    @pet = Pet.random
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  # def create
  #   @pet = Pet.new( pet_params)
  #
  #   respond_to do |format|
  #     if @pet.save
  #       format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
  #       format.json { render :show, status: :created, location: @pet }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @pet.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  # def update
  #   respond_to do |format|
  #     if @pet.update(pet_params)
  #       format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @pet }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @pet.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /pets/1
  # # DELETE /pets/1.json
  # def destroy
  #   @pet.destroy
  #   respond_to do |format|
  #     format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :image, :species, :breed, :gender, :age, :size, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to '/'
      else
        redirect_to '/signup'
      end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<div class="container">
  <div class= "header">
    <nav id="nav-main">
<ul>
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Favorites", favorites_path%></li>
  <li><%= link_to "Login", login_path%></li>
  <li><%= link_to "Sign Up", signup_path%></li>
</ul>
</nav>
<div id="nav-trigger">
<span>Menu</span>
</div>
<nav id="nav-mobile"></nav>
</div>

<!-- CAROUSEL/DESCRIPTION////////// -->
     <div class="headerbox" id="w_name">
      <span id="adanim">adopt</span><span id="apanim">Petz</span>
    </div>

<div class= "favorite">
<% @favorites.each do |fav| %>
  <div class="fav-pet">
    <figure>
      <%=image_tag(fav.pet.image) %>
      <figcaption><%=fav.pet.name%></figcaption>
    </figure>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adopt Pets</title>
    <%= csrf_meta_tags %> 


    <!-- GOOGLE FONT/////////// -->
      <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.0/animate.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.0/animate.min.css">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

 </head>

  <body>

    <!-- <div class="container">
      <div class= "header">
        <nav id="nav-main">
          <ul>
            <li><a href="">Home</a></li>
            <li><%=link_to 'My Favorites', favorites_path %></li>
            <li><a href="">About Us</a></li>
            <li><a href="">Shelter</a></li>
          </ul>
        </nav>
        <div id="nav-trigger">
            <span>Menu</span>
        </div>
        <nav id="nav-mobile"></nav>
      </div> -->

<!-- CAROUSEL/DESCRIPTION////////// -->


    <%= yield %>


    <!--TOD Need file content  -->



  </body>
</html>

app/views/pets/_form.html.erb
<%= form_for(pet) do |f| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :breed %>
    <%= f.text_field :breed %>
  </div>

  <div class="field">
    <%= f.label :sex %>
    <%= f.text_field :sex %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>

  <div class="field">
    <%= f.label :size %>
    <%= f.text_field :size %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Species</th>
      <th>Breed</th>
      <th>Gender</th>
      <th>Age</th>
      <th>Size</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.image %></td>
        <td><%#= pet.species %></td>
        <td><%#= pet.breed %></td>
        <td><%#= pet.gender %></td>
        <td><%#= pet.age %></td>
        <td><%#= pet.size %></td>
        <td><%#= pet.description %></td>
        <td><%#= link_to 'Show', pet %></td>
        <td><%#= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%#= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/show.html.erb
<!-- MODAL /////////// -->
 <a id="demo01" href="#animatedModal"></a>
  <div id="animatedModal" class="animated animatedModal-off">

    <div id="closebt-container" class="close-animatedModal">
      <div class='close-btn-container'>
        <%= image_tag('closebt.svg', :alt => 'Close', :class => 'closebt') %>
      </div>
    </div>

    <div class="modal-content">
      <p class="welcome">Welcome</p>
      <div class="text">
        <p>
          <span class="main_st"><span id="ap">adoptPetz</span> is the place where you can meet your new best friend with the click of a button.</span>
        </p>
        <p>Please <span class="sign_in">Sign-In</span> or <span class="login">Login</span> to make the best out of your experience!</p>
        <p><span id="find">Finding your best friend has never been easier.</span><br><br> After making an account, a picture of an adoptable friend will show up.</p> <p>Click the Happy Dog and add them to your Favorites. The Mad Cat will scroll to the next friend.</p>
        <p><span id="find">Have <span id="ap">fun</span>!</span></p>
      </div>
    </div>
  </div>
    <div class="container">
      <div class= "header">
        <nav id="nav-main">
    <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Favorites", favorites_path%></li>
        <li><%= link_to "Login", login_path%></li>
        <li><%= link_to "Sign Up", signup_path%></li>
    </ul>
</nav>
<div id="nav-trigger">
    <span>Menu</span>
</div>
<nav id="nav-mobile"></nav>
    </div>

<!-- CAROUSEL/DESCRIPTION////////// -->
         <div class="headerbox" id="w_name">
          <span id="adanim">adopt</span><span id="apanim">Petz</span>
        </div>
        <div class="carousel"><div class="img_center">
          <%= image_tag(@pet.image, :id => "petimage", alt: "") %>
        </div>
    </div>
  </div>
    <!-- LIKE/DISLIKE/////////// -->
       <div class= "likebuttons">
        <div class="like">
          <div id="likedog">
            <%= image_tag('likedogNoBG2.png', :alt => "like") %>
            <div id="petid"><%= @pet.id %></div>
          </div>
        </div>
        <div class="dislike">
          <div id="dislikecat">
            <%= image_tag('dislikecatNoBG2.png', :alt => "dislike") %>
          </div>
        </div>
      </div>

<!-- FOOTER////////// -->
     <div class="pet_info">
        <ul>
         <li><strong>Name:</strong>
           <scan id="petname"><%= @pet.name %></scan>
         </li>
          <li><strong>Breed:</strong>
            <scan id="petbreed">
              <%= @pet.breed %>
            </scan>
          </li>
          <li><strong>Sex:</strong>
            <scan id="petsex">
              <%= @pet.sex %>
            </scan>
          </li>
          <li><strong>Age:</strong>
            <scan id="petage">
              <%= @pet.age %>
            </scan>
          </li>
          <li><strong>Size:</strong>
            <scan id="petsize">
              <%= @pet.size %>
            </scan>
          </li>
          <li><strong>Description:</strong>
            <scan id="petdescript">
              <%= @pet.description %>
            </scan>
          </li>
        </ul>
    </div>

<p id="notice"><%= notice %></p>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container">

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
  <div class= "header">
    <nav id="nav-main">
<ul>
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Favorites", favorites_path%></li>
  <li><%= link_to "Login", login_path%></li>
  <li><%= link_to "Sign Up", signup_path%></li>
</ul>
</nav>
<div id="nav-trigger">
<span>Menu</span>
</div>
<nav id="nav-mobile"></nav>
</div>

<!-- CAROUSEL/DESCRIPTION////////// -->
     <div class="headerbox" id="w_name">
      <span id="adanim">adopt</span><span id="apanim">Petz</span>
    </div>

    <div class= "sign_up">

<%= form_for :user, url: '/users' do |f| %>
<ul class="login">
  <li class="name"><%= f.text_field :name, placeholder: "Name" %></li>
  <li id="email"><%= f.text_field :email, placeholder: "Email" %></li>
  <li id="pw"><%= f.password_field :password, placeholder: "Password" %></li>
  <li id="conf"> <%= f.password_field :password_confirmation , placeholder: "Confirm Password" %></li>
  <li id="submit"><%= f.submit "Register" %></li>
</ul></div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>